name: messenger
description: Messenger App

version: 1.0.0+1

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^0.7.0

flutter:
  uses-material-design: true
